# Generated by Django 3.1.2 on 2021-01-26 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_delete_orderupdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='amount',
        ),
    ]
